# Generated by Django 4.2 on 2023-07-08 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('m_prod', '0002_alter_producto_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boleta',
            name='numero_carrito',
        ),
    ]
