# Generated by Django 4.2 on 2023-07-07 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('m_prod', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleBoleta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('boleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='m_prod.boleta')),
            ],
        ),
    ]
